name: Android Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Name'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

permissions:
  contents: write # to fetch code (actions/checkout), push tag

jobs:
  android_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          submodules: true
          fetch-depth: 0
      - name: Set env
        id: last_tag
        run: echo "LAST_TAG=$(git tag --sort=committerdate | tail -1)" >> $GITHUB_OUTPUT
      - uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        with:
          current_version: ${{ steps.last_tag.outputs.LAST_TAG }}
          # A semver update level {major, minor, patch}.
          level: ${{ github.event.inputs.version }}
      - run: |
          git config user.name abkhare
          git config user.email abhiraj.khare100@gmail.com
          git tag ${{ steps.bump-semver.outputs.new_version }}
          git push --tags
      - uses: winterjung/split@v2
        id: split
        with:
          separator: '.'
          msg: ${{ steps.bump-semver.outputs.new_version }}
      - name: "Set output"
        id: set-output
        run: |
          echo "mobile_version_name=${{ steps.bump-semver.outputs.new_version }}" >> $GITHUB_OUTPUT

          IFS='.' read -r major minor patch <<< "${{ steps.bump-semver.outputs.new_version }}"
          mobile_version_code=$((steps.split.outputs._0 * 10000 + steps.split.outputs._1 * 100 + steps.split.outputs._2))

          echo "mobile_version_code=${mobile_version_code}" >> $GITHUB_OUTPUT
      - name: "Print output"
        run: |
          echo -e "Version name is: \n ${{ steps.set-output.outputs.mobile_version_name }}"
          echo -e "Version code is: \n ${{ steps.set-output.outputs.mobile_version_code }}"

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew :app:assembleDebug

      - name: GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.set-output.outputs.mobile_version_name }}
          release_name: Android Release .${{ steps.set-output.outputs.mobile_version_name }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Upload Release APK
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/build/outputs/apk/debug/app-debug.apk
          asset_name: signed-artifact.apk
          asset_content_type: application/zip