name: Android CI

on:
  push:
    branches: [ "feature/workflows" ]
  pull_request:
    branches: [ "feature/workflows" ]

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build:

    runs-on: ubuntu-latest-8-cores

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew :app:assembleDebug
