name: Android CI

on:
  push:
    branches: [ "feature/workflows" ]
  pull_request:
      branches: [ "feature/workflows" ]

jobs:
  android_deploy:
    needs: [prepare_deploy]
    env:
      APP_VERSION_NAME: ${{ needs.prepare_deploy.outputs.mobile_version_name }}
      APP_VERSION_CODE: ${{ needs.prepare_deploy.outputs.mobile_version_code }}
    runs-on: ubuntu-latest
    steps:
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew :app:assembleDebug

      - name: GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.APP_VERSION_NAME }}
          release_name: Android Release .${{ env.APP_VERSION_NAME }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Upload Release APK
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/build/outputs/apk/debug/app-debug.apk
          asset_name: signed-artifact.apk
          asset_content_type: application/zip